### ISSUE TITLE
機能要望：ルビのフォントサイズを調整できるオプションの追加

### ISSUE THREAD

**Issue by Kobamiyannnn** [k-quels/japanese-novel-ruby#1]
プラグインの本来の用途とは異なるのですが、英語論文を読む際に、英語のテキストに日本語訳のルビを振れる点が非常に便利でJapanese Novel Rubyを重宝しています。一般的にルビは親文字の半分のフォントサイズとされているようですが、こうした用途ではルビに漢字を使うことが多く、文字が潰れて非常に読みづらく感じます。そこで、可読性を向上させるために、ルビのフォントサイズを自由に変更できるオプションを追加していただけないでしょうか？
　現在はCSSスニペットを利用してルビのフォントサイズを変更していますが、直感的に操作できるように設定画面にオプションとして実装していただけると幸いです。ご検討のほどよろしくお願いいたします。

**Comment by k-quels** [comment]
ご意見ありがとうございます。
こちら1.1.1で対応してみましたので、よろしければご利用下さい！

**Comment by Kobamiyannnn** [comment]
年末休暇中にもかかわらず迅速にご対応いただき、ありがとうございます🙏
これからもありがたく使わせていただきます！
